"""Credential Injector — generates temporary .env files with TTL.

Produces a .env file and a sidecar .env.vault-meta for validation.
The .env contains actual secret values; the meta file tracks expiration.
"""

import hashlib
import json
import logging
import os
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger("credential_vault.injector")


def generate_env_file(project: str, citizen: str, secrets_dict: Dict[str, str],
                      project_path: str, ttl_hours: int = 24) -> Dict[str, Any]:
    """Generate a .env file with secret values and a sidecar meta file.

    Args:
        project: Project name (e.g. 'fetching')
        citizen: Citizen email
        secrets_dict: {env_var_name: secret_value}
        project_path: Absolute path to the project directory
        ttl_hours: Time-to-live in hours for the generated .env

    Returns:
        Dict with injection metadata (id, paths, expiration)
    """
    now = datetime.now(timezone.utc)
    expires_at = now + timedelta(hours=ttl_hours)

    env_path = Path(project_path) / ".env"
    meta_path = Path(project_path) / ".env.vault-meta"

    lines = [f"# Generated by AI Governor — expires {expires_at.isoformat()}"]
    lines.append(f"# Project: {project} | Citizen: {citizen}")
    lines.append(f"# DO NOT commit this file. Regenerate with: /governor.env inject {project}")
    lines.append("")
    for var, value in secrets_dict.items():
        lines.append(f"{var}={value}")

    env_content = "\n".join(lines) + "\n"

    checksum = hashlib.sha256(env_content.encode()).hexdigest()

    meta = {
        "citizen": citizen,
        "project": project,
        "generated_at": now.isoformat(),
        "expires_at": expires_at.isoformat(),
        "secrets": list(secrets_dict.keys()),
        "checksum": f"sha256:{checksum}",
    }

    env_path.write_text(env_content)
    meta_path.write_text(json.dumps(meta, indent=2) + "\n")

    ensure_gitignore(project_path)

    logger.info("Generated .env for %s/%s (expires %s)", project, citizen, expires_at.isoformat())

    return {
        "env_path": str(env_path),
        "meta_path": str(meta_path),
        "expires_at": expires_at.isoformat(),
        "variables": list(secrets_dict.keys()),
        "checksum": checksum,
    }


def generate_vault_meta(injection_id: str, citizen: str, project: str,
                        secrets_names: List[str], ttl_hours: int = 24) -> Dict[str, Any]:
    """Create injection record metadata for vault_injections.yaml."""
    now = datetime.now(timezone.utc)
    return {
        "id": injection_id,
        "citizen": citizen,
        "project": project,
        "secrets_injected": secrets_names,
        "generated_at": now.isoformat(),
        "expires_at": (now + timedelta(hours=ttl_hours)).isoformat(),
        "status": "active",
        "revoked_by": None,
    }


def ensure_gitignore(project_path: str) -> bool:
    """Ensure .env and .env.vault-meta are in .gitignore. Returns True if modified."""
    gitignore = Path(project_path) / ".gitignore"
    patterns = [".env", ".env.vault-meta"]

    existing_lines = set()
    existing_text = ""
    if gitignore.exists():
        existing_text = gitignore.read_text()
        existing_lines = {line.strip() for line in existing_text.splitlines()}

    missing = [p for p in patterns if p not in existing_lines]
    if not missing:
        return False

    with open(gitignore, "a") as f:
        if existing_text and not existing_text.endswith("\n"):
            f.write("\n")
        for p in missing:
            f.write(f"{p}\n")

    logger.info("Added %s to .gitignore in %s", missing, project_path)
    return True


def validate_meta(meta_path: str) -> bool:
    """Check if an injection is still valid (not expired, not revoked)."""
    path = Path(meta_path)
    if not path.exists():
        return False

    try:
        meta = json.loads(path.read_text())
    except (json.JSONDecodeError, OSError):
        return False

    expires_at = datetime.fromisoformat(meta.get("expires_at", ""))
    return datetime.now(timezone.utc) < expires_at


