"""
Kōan -- CLAUDE.md refresh pipeline.

Analyzes recent commits in a project and updates (or creates) the CLAUDE.md
file with architecturally significant changes.

Usage:
    python -m app.claudemd_refresh <project_path> [--project-name NAME]

Pipeline:
1. Detect whether CLAUDE.md exists in the project
2. Gather git context (commits since last CLAUDE.md modification)
3. Create a feature branch
4. Build a selective prompt focused on architectural changes
5. Invoke Claude CLI to update/create CLAUDE.md
6. Commit, push, and create a draft PR
"""

import argparse
import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

from app.claude_step import _commit_with_hook_fallback
from app.git_sync import run_git
from app.git_utils import run_git_strict
from app.prompts import load_skill_prompt
from app.skill_memory import build_memory_block_for_skill

# --- Kōan-learnings managed block --------------------------------------------
# The `learnings` mode of /claudemd distills durable conventions out of a
# project's private learnings.md and writes them into a delimited, regenerable
# block inside CLAUDE.md. Delimiting the block is the anti-overlap guarantee:
# re-syncs replace only this region in place, so content never accumulates and
# human-authored prose is left untouched.
KOAN_LEARNINGS_BEGIN = (
    "<!-- BEGIN KOAN LEARNINGS (auto-generated by `/claudemd <project> "
    "learnings` — do not edit by hand) -->"
)
KOAN_LEARNINGS_END = "<!-- END KOAN LEARNINGS -->"

_BLOCK_RE = re.compile(
    re.escape(KOAN_LEARNINGS_BEGIN) + r".*?" + re.escape(KOAN_LEARNINGS_END),
    re.DOTALL,
)

_NO_DURABLE_SENTINEL = "NO_DURABLE_LEARNINGS"


def _render_learnings_block(distilled: str) -> str:
    """Render the full managed block (markers + heading + body)."""
    return (
        f"{KOAN_LEARNINGS_BEGIN}\n"
        "## Learnings from Kōan\n\n"
        "_Conventions Kōan distilled from its autonomous work on this "
        "project. Regenerated by `/claudemd <project> learnings` — edit the "
        "source learnings, not this block._\n\n"
        f"{distilled.strip()}\n"
        f"{KOAN_LEARNINGS_END}"
    )


def upsert_koan_learnings_block(existing: str, distilled: str) -> str:
    """Insert or replace the Kōan-learnings managed block in CLAUDE.md text.

    - If the markers already exist, the region between them is replaced
      in place (a lambda replacement keeps regex metacharacters in
      ``distilled`` literal — a string replacement would interpret ``\\1`` /
      ``\\g<0>`` backreferences).
    - Otherwise the block is appended after the existing content.

    All non-block content is preserved verbatim. The result always ends in
    exactly one newline.
    """
    block = _render_learnings_block(distilled)
    if KOAN_LEARNINGS_BEGIN in existing and KOAN_LEARNINGS_END in existing:
        return _BLOCK_RE.sub(lambda _m: block, existing, count=1).rstrip("\n") + "\n"
    base = existing.rstrip("\n")
    if base:
        return f"{base}\n\n{block}\n"
    return f"{block}\n"


def _git_last_modified(project_path: str, filepath: str) -> str:
    """Get the ISO date of the last commit that modified a file.

    Returns empty string if the file has never been committed.
    """
    return run_git(project_path, "log", "-1", "--format=%aI", "--", filepath)


def _git_log_since(project_path: str, since_date: str, max_commits: int = 50) -> str:
    """Get git log since a date, formatted for context."""
    return run_git(
        project_path, "log",
        f"--since={since_date}", f"-n{max_commits}",
        "--format=%h %s", "--no-merges",
    )


def _git_diff_stat_since(project_path: str, since_date: str) -> str:
    """Get diffstat of changes since a date (files changed, not content)."""
    # Find the oldest commit since that date
    log_output = run_git(
        project_path, "log", f"--since={since_date}", "--format=%H", "--reverse",
    )
    commits = log_output.splitlines()
    if not commits:
        return ""
    oldest = commits[0]
    # Check if oldest commit has a parent (fails on root commit)
    has_parent = bool(run_git(project_path, "rev-parse", "--verify", f"{oldest}^"))
    diff_range = f"{oldest}..HEAD" if not has_parent else f"{oldest}~1..HEAD"
    return run_git(project_path, "diff", "--stat", diff_range)


def _git_log_full(project_path: str, max_commits: int = 30) -> str:
    """Get recent git log for INIT mode (no CLAUDE.md exists yet)."""
    return run_git(
        project_path, "log", f"-n{max_commits}", "--format=%h %s", "--no-merges",
    )


def build_git_context(project_path: str, claude_md_exists: bool) -> str:
    """Build the git context section for the prompt."""
    if not claude_md_exists:
        recent = _git_log_full(project_path)
        if recent:
            return f"No CLAUDE.md exists yet. Recent project history:\n\n```\n{recent}\n```"
        return "No CLAUDE.md exists yet. No git history available."

    last_modified = _git_last_modified(project_path, "CLAUDE.md")
    if not last_modified:
        # CLAUDE.md exists but was never committed (maybe .gitignored or new)
        recent = _git_log_full(project_path, max_commits=20)
        return (
            "CLAUDE.md exists but has no git history (uncommitted or new).\n"
            f"Recent commits:\n\n```\n{recent}\n```"
        )

    commits = _git_log_since(project_path, last_modified)
    if not commits:
        return (
            f"CLAUDE.md was last updated: {last_modified}\n\n"
            "No new commits since then. CLAUDE.md is up to date."
        )

    diffstat = _git_diff_stat_since(project_path, last_modified)

    context = f"CLAUDE.md was last updated: {last_modified}\n\n"
    context += f"Commits since then ({len(commits.splitlines())} total):\n\n```\n{commits}\n```"
    if diffstat:
        context += f"\n\nFiles changed (diffstat):\n\n```\n{diffstat}\n```"
    return context


def _has_changes(project_path: str) -> bool:
    """Check if there are uncommitted changes in the working tree."""
    result = subprocess.run(
        ["git", "status", "--porcelain"],
        capture_output=True, text=True, cwd=project_path, timeout=30,
    )
    if result.returncode != 0:
        print(
            f"[claudemd] git status failed (rc={result.returncode}): "
            f"{result.stderr.strip()}", file=sys.stderr,
        )
        return False
    return bool(result.stdout.strip())


def _create_branch(project_path: str, branch_name: str) -> None:
    """Create and checkout a new branch from the current HEAD."""
    run_git_strict("checkout", "-b", branch_name, cwd=project_path)


def _commit_and_push(project_path: str, branch_name: str, message: str) -> bool:
    """Stage CLAUDE.md, commit, and push. Returns True if a commit was created."""
    if not _has_changes(project_path):
        return False
    run_git_strict("add", "CLAUDE.md", cwd=project_path)

    def _runner(cmd, cwd=None, timeout=60):
        # Adapt _run_git convention (cmd list) to run_git_strict (*args).
        return run_git_strict(*cmd[1:], cwd=cwd, timeout=timeout)

    _commit_with_hook_fallback(["-m", message], project_path, _runner)
    run_git_strict("push", "-u", "origin", branch_name, cwd=project_path)
    return True


def _create_pr(
    project_path: str,
    project_name: str,
    mode: str,
    base_branch: str,
) -> str:
    """Create a draft PR for the CLAUDE.md update. Returns the PR URL."""
    import os

    from app.github import pr_create, resolve_target_repo
    from app.pr_footer import append_koan_footer, build_pr_footer

    started_at_raw = os.environ.get("KOAN_MISSION_STARTED_AT", "")
    try:
        started_at = float(started_at_raw) if started_at_raw else None
    except ValueError:
        started_at = None

    footer = build_pr_footer(
        project_name=project_name,
        project_path=project_path,
        started_at=started_at,
    )
    if mode == "INIT":
        title = f"docs: create CLAUDE.md for {project_name}"
        body = append_koan_footer(
            (
                "## What\n"
                f"Create initial CLAUDE.md for **{project_name}**.\n\n"
                "## Why\n"
                "No CLAUDE.md existed — this bootstraps the reference document "
                "for AI coding assistants working on this project."
            ),
            footer,
        )
    elif mode == "LEARNINGS":
        title = f"docs: sync Kōan learnings into CLAUDE.md for {project_name}"
        body = append_koan_footer(
            (
                "## What\n"
                f"Distill Kōan's per-project learnings for **{project_name}** "
                "into the managed `## Learnings from Kōan` block in CLAUDE.md.\n\n"
                "## Why\n"
                "Interactive Claude Code sessions don't see Kōan's private "
                "`instance/memory` — this surfaces the durable conventions Kōan "
                "discovered so any AI assistant on this repo benefits. Only the "
                "delimited managed block changes; existing content is untouched."
            ),
            footer,
        )
    else:
        title = f"docs: update CLAUDE.md for {project_name}"
        body = append_koan_footer(
            (
                "## What\n"
                f"Update CLAUDE.md for **{project_name}** to reflect recent changes.\n\n"
                "## Why\n"
                "Architecturally significant changes landed since the last update. "
                "This keeps the AI reference document in sync with the codebase."
            ),
            footer,
        )

    pr_kwargs = {
        "title": title,
        "body": body,
        "draft": True,
        "base": base_branch,
        "cwd": project_path,
    }

    # Target upstream repo when working in a fork
    upstream = resolve_target_repo(
        project_path, project_name=project_name,
    )
    if upstream:
        pr_kwargs["repo"] = upstream
        try:
            from app.pr_submit import get_fork_owner
            fork_owner = get_fork_owner(project_path)
            if fork_owner:
                from app.git_utils import get_current_branch
                branch = get_current_branch(cwd=project_path)
                pr_kwargs["head"] = f"{fork_owner}:{branch}"
        except Exception as exc:
            import logging
            logging.getLogger(__name__).debug("Fork owner detection failed: %s", exc)

    return pr_create(**pr_kwargs)


def run_refresh(project_path: str, project_name: str) -> int:
    """Run the CLAUDE.md refresh pipeline.

    Returns:
        0 on success, 1 on failure.
    """
    from app.claude_step import run_claude
    from app.cli_provider import build_full_command
    from app.config import get_branch_prefix, get_model_config, get_skill_max_turns

    project_path = str(Path(project_path).resolve())
    claude_md = Path(project_path) / "CLAUDE.md"
    claude_md_exists = claude_md.exists()

    if claude_md_exists:
        mode = "UPDATE"
        mode_instructions = (
            "CLAUDE.md already exists. Analyze the recent commits to find "
            "architecturally significant changes and update the file accordingly. "
            "Make minimal, surgical edits. If nothing significant changed, say so."
        )
        # Gather git context (before branching, so we see main's history)
        git_context = build_git_context(project_path, True)

        # Check if there's nothing to do
        if "No new commits since then" in git_context:
            print("CLAUDE.md is up to date — no new commits since last update.")
            return 0
    else:
        mode = "INIT"
        mode_instructions = (
            "No CLAUDE.md exists yet. Explore the project structure, read key "
            "files (README, package manifests, entry points, tests), and create "
            "a comprehensive CLAUDE.md from scratch."
        )
        git_context = build_git_context(project_path, False)

    # Remember the base branch for the PR
    base_branch = run_git_strict(
        "rev-parse", "--abbrev-ref", "HEAD", cwd=project_path,
    ).strip()

    # Create a feature branch (timestamp avoids collision with stale branches)
    prefix = get_branch_prefix()
    ts = datetime.now(timezone.utc).strftime("%Y%m%d%H%M")
    branch_name = f"{prefix}update-claudemd-{project_name}.{ts}"
    try:
        _create_branch(project_path, branch_name)
    except (RuntimeError, subprocess.SubprocessError) as e:
        print(f"Failed to create branch {branch_name}: {e}", file=sys.stderr)
        return 1

    # Claude provider has a built-in /init skill — use it directly
    from app.config import get_cli_provider_name
    if mode == "INIT" and get_cli_provider_name() == "claude":
        prompt = "/init"
    else:
        task_text = f"CLAUDE.md {'refresh' if claude_md_exists else 'creation'} for {project_name}\n{git_context}"
        project_memory = build_memory_block_for_skill(project_path, task_text)

        skill_dir = Path(__file__).parent.parent / "skills" / "core" / "claudemd"
        prompt = load_skill_prompt(
            skill_dir, "refresh-claude-md",
            MODE=mode,
            MODE_INSTRUCTIONS=mode_instructions,
            PROJECT_PATH=project_path,
            PROJECT_NAME=project_name,
            GIT_CONTEXT=git_context,
            PROJECT_MEMORY=project_memory,
        )

    # Build CLI command
    models = get_model_config()
    cmd = build_full_command(
        prompt=prompt,
        allowed_tools=["Bash", "Read", "Write", "Edit", "Glob", "Grep"],
        model=models.get("mission", ""),
        fallback=models.get("fallback", ""),
        max_turns=get_skill_max_turns(),
    )

    # Run Claude to edit CLAUDE.md
    result = run_claude(cmd, project_path, timeout=300)

    if not result["success"]:
        # Return to base branch on failure
        run_git_strict("checkout", base_branch, cwd=project_path)
        print(f"CLAUDE.md refresh failed: {result['error']}", file=sys.stderr)
        return 1

    print(result["output"])

    # Commit, push, and create PR
    commit_msg = (
        f"docs: {'create' if mode == 'INIT' else 'update'} CLAUDE.md"
    )
    try:
        committed = _commit_and_push(project_path, branch_name, commit_msg)
    except (RuntimeError, subprocess.SubprocessError) as e:
        run_git_strict("checkout", base_branch, cwd=project_path)
        print(f"Failed to commit/push: {e}", file=sys.stderr)
        return 1

    if not committed:
        # Claude decided no changes were needed
        run_git_strict("checkout", base_branch, cwd=project_path)
        print("No changes to CLAUDE.md — nothing to commit.")
        return 0

    try:
        pr_url = _create_pr(project_path, project_name, mode, base_branch)
        print(f"PR created: {pr_url.strip()}")
    except (RuntimeError, subprocess.SubprocessError) as e:
        print(f"Branch pushed but PR creation failed: {e}", file=sys.stderr)

    # Return to the base branch
    run_git_strict("checkout", base_branch, cwd=project_path)
    return 0


def _read_project_learnings(project_name: str) -> str:
    """Read this project's learnings.md from the Kōan instance tree.

    Returns "" when KOAN_ROOT is unset or the file is missing/empty.
    """
    koan_root = os.environ.get("KOAN_ROOT", "")
    if not koan_root:
        return ""
    path = (
        Path(koan_root) / "instance" / "memory" / "projects"
        / project_name / "learnings.md"
    )
    if not path.is_file():
        return ""
    try:
        return path.read_text(encoding="utf-8")
    except OSError as e:
        print(f"[claudemd] learnings read failed: {e}", file=sys.stderr)
        return ""


def _distill_learnings_cli(
    learnings: str, current_claude_md: str, project_path: str,
) -> str:
    """Distill durable conventions from raw learnings via the lightweight CLI.

    Stdout-only (no file tools, max_turns=1), mirroring
    memory_manager._run_compaction_cli. Returns the raw model stdout.
    """
    from app.cli_exec import run_cli_with_retry
    from app.cli_provider import build_full_command
    from app.config import get_model_config

    skill_dir = Path(__file__).parent.parent / "skills" / "core" / "claudemd"
    prompt = load_skill_prompt(
        skill_dir, "sync-learnings",
        PROJECT_NAME=Path(project_path).name,
        LEARNINGS=learnings,
        CURRENT_CLAUDE_MD=current_claude_md or "(no CLAUDE.md exists yet)",
    )
    models = get_model_config()
    cmd = build_full_command(
        prompt=prompt,
        allowed_tools=[],
        model=models.get("lightweight", "haiku"),
        fallback=models.get("fallback", "sonnet"),
        max_turns=1,
    )
    result = run_cli_with_retry(
        cmd, capture_output=True, text=True, timeout=180, cwd=project_path,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"distill CLI returned {result.returncode}: {result.stderr[:200]}"
        )
    return result.stdout.strip()


def run_learnings_sync(project_path: str, project_name: str) -> int:
    """Sync Kōan's per-project learnings into the project's CLAUDE.md.

    Reads learnings.md, distills durable conventions, writes them into the
    managed block, and opens a draft PR. Returns 0 on success or clean
    no-op, 1 on failure.
    """
    from app.config import get_branch_prefix
    from app.utils import atomic_write

    project_path = str(Path(project_path).resolve())
    claude_md = Path(project_path) / "CLAUDE.md"

    learnings = _read_project_learnings(project_name)
    if not learnings.strip():
        print(f"No learnings recorded for {project_name} — nothing to sync.")
        return 0

    existing = claude_md.read_text(encoding="utf-8") if claude_md.exists() else ""

    try:
        distilled = _distill_learnings_cli(learnings, existing, project_path)
    except Exception as e:
        print(f"Learnings distillation failed: {e}", file=sys.stderr)
        return 1

    if not distilled.strip() or distilled.strip() == _NO_DURABLE_SENTINEL:
        print("No durable, CLAUDE.md-worthy conventions found in learnings.")
        return 0

    updated = upsert_koan_learnings_block(existing, distilled)
    if updated == existing:
        print("CLAUDE.md Kōan-learnings block already up to date.")
        return 0

    # Remember the base branch for the PR / rollback.
    base_branch = run_git_strict(
        "rev-parse", "--abbrev-ref", "HEAD", cwd=project_path,
    ).strip()

    prefix = get_branch_prefix()
    ts = datetime.now(timezone.utc).strftime("%Y%m%d%H%M")
    branch_name = f"{prefix}sync-learnings-{project_name}.{ts}"
    try:
        _create_branch(project_path, branch_name)
    except (RuntimeError, subprocess.SubprocessError) as e:
        print(f"Failed to create branch {branch_name}: {e}", file=sys.stderr)
        return 1

    atomic_write(claude_md, updated)

    try:
        committed = _commit_and_push(
            project_path, branch_name, "docs: sync Kōan learnings into CLAUDE.md",
        )
    except (RuntimeError, subprocess.SubprocessError) as e:
        run_git_strict("checkout", base_branch, cwd=project_path)
        print(f"Failed to commit/push: {e}", file=sys.stderr)
        return 1

    if not committed:
        run_git_strict("checkout", base_branch, cwd=project_path)
        print("No changes to CLAUDE.md — nothing to commit.")
        return 0

    try:
        pr_url = _create_pr(project_path, project_name, "LEARNINGS", base_branch)
        print(f"PR created: {pr_url.strip()}")
    except (RuntimeError, subprocess.SubprocessError) as e:
        print(f"Branch pushed but PR creation failed: {e}", file=sys.stderr)

    run_git_strict("checkout", base_branch, cwd=project_path)
    return 0


def main():
    parser = argparse.ArgumentParser(
        description="Refresh or create CLAUDE.md for a project",
    )
    parser.add_argument("project_path", help="Path to the project directory")
    parser.add_argument(
        "--project-name", default="",
        help="Project name (defaults to directory basename)",
    )
    parser.add_argument(
        "--mode", choices=["refresh", "learnings"], default="refresh",
        help="refresh = git-history-driven update; learnings = sync memory learnings",
    )
    args = parser.parse_args()

    project_name = args.project_name or Path(args.project_path).name

    if args.mode == "learnings":
        sys.exit(run_learnings_sync(args.project_path, project_name))
    sys.exit(run_refresh(args.project_path, project_name))


if __name__ == "__main__":
    main()
